### ISSUE TITLE
Move to Treshhold Signing

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#166]
Currently we require all the nodes to sign the transaction before it can be sent to the Relayer. It means that our service will not work if one of the nodes is down. Treshhold signing should allow us to elliminte this risk.

Same goes for the case when one of the nodes lose their key. It will make key recovery impossible for all the users.

This issues is still under consideration since it's a big effort and we can move to other design (recovery contract, for example).

**Comment by itegulov** [comment]
Closing in favor of #326
