### ISSUE TITLE
Extend feature environments with frontend

### ISSUE THREAD

**Issue by itegulov** [near/mpc-recovery#203]
Having backend deployed is great and all, but its usefulness is dubios without also having an accompanying frontend. Shouldn't be too hard in principle, but unclear what branch we should be deploying by default and whether it should be customizable.

**Comment by DavidM-D** [comment]
Is this ready now?

**Comment by volovyks** [comment]
Looks like we will change our design to have only one test environment. It will be updated on request from any PR.
I do not think that we need to spin FE with it, do not forget that we will have staging env.
cc @itegulov what do you think? Should we close this issue?

**Comment by itegulov** [comment]
Since we are moving to a static feature enviornment I agree that we can close this
