### ISSUE TITLE
Open Source this repository

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc-recovery#206]
Let's open source this repository. What's the bare minimum we need to do to achieve that?

I'm not worried about being embarrassed about having old issues and old commits around. I'll sort out the licensing stuff. What else is there?
```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/258
```

**Comment by volovyks** [comment]
@itegulov yep, turned on, thanks.
Changed this setting to be more strict:
<img width="785" alt="image" src="https://github.com/near/mpc-recovery/assets/4030422/931c07e9-8b41-4eb4-8acd-12d9519f9ee7">
