### ISSUE TITLE
Add Popula to MPC Service

### ISSUE THREAD

**Issue by diogoortega** [near/mpc-recovery#314]
Popula.io is ready to be added to MPC Service.

You can find their Firebase ID, Relayer API Key, and Relayer URL [here](https://docs.google.com/spreadsheets/d/1o52IO2MVvhCrtpK0RvzBoUWNaMIl5vKv7w3oML0BqHA/edit?usp=sharing).

**Comment by volovyks** [comment]
Blocked by #315

**Comment by volovyks** [comment]
@diogoortega added to prod env, but we still need to release the new version of the MPC.
