### ISSUE TITLE
Add allert when MPC service is not operational

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#338]
In case MPC Server is down we should get the coressponding Slack notification.
Optional: distinguish it from reboots.

**Comment by volovyks** [comment]
@kmaus-near will it trigger a message in Slack?
Have you added it to both the Leader node and our signing node?

**Comment by kmaus-near** [comment]
@volovyks Yes to both. 

Also I noticed Mainnet is using 2 dev signers. Is this intentional?

**Comment by itegulov** [comment]
@kmaus-near yeah there was an old mainnet environment up that we kept just in case. I have just destroyed it since it seems like we are fairly stable now.

**Comment by volovyks** [comment]
K, thanks @kmaus-near, closing.
