### ISSUE TITLE
Vote kick mechanism

### ISSUE THREAD

**Issue by itegulov** [near/mpc-recovery#353]
### Description

We already have a vote kick mechanism implemented in the contract (see `vote_leave`), but it is not actually being used as we have not decided on the criteria when a node should vote to kick someone else. I propose to do something very simple for now - occasionally every node pings every other node and if they see three consecutive fails then they vote to kick it out of the participant set. This is essential to keep throughput high as a single faulty node can sabotage ~66% of sign requests.

We can improve the criteria in the future when we have identifiable aborts.

**Comment by volovyks** [comment]
In the current design and the concept of Active Participants, we do not need this functionality. Each partner can call vote_leave with CLI.
