### ISSUE TITLE
Serialize cryptographic primitives to the correct signature format used in NEAR ecosystem

### ISSUE THREAD

**Issue by itegulov** [near/mpc-recovery#386]
### Description

The contract response API looks like this:
```rust
pub fn respond(&mut self, receipt_id: [u8; 32], big_r: String, s: String) {}
```

Meaning it accepts $R$ and $s$ in a very raw and direct form. NEAR has a specific signature serialization format that I failed to reverse engineer so far. I have tried various small variations of the following which didn't work, but feel free to try it again in case I did something wrong:
```
big_r.x().to_big_endian_bytes() ++ s.to_big_endian_bytes() ++ [2 if big_r.y() is even, 3 otherwise]
```

**Comment by volovyks** [comment]
Now we are moving away from near_crypto and near_sdk primitives in favour of wider industry standards. We will keep returning R and s values.
