### ISSUE TITLE
Consider constraining protocol loop to one second including all work needed

### ISSUE THREAD

**Issue by ChaoticTempest** [near/mpc-recovery#388]
Currently, we have a `sleep(1sec)` in our protocol loop for multichain. This might lead us to having a single iteration of this loop go unbounded in time. How about we constrain it to be exactly one second, and then the `sleep(1sec)` call becomes `sleep(1sec - work_time_taken)`. This way we can have a fixed amount of time spent in each loop iteration and also be able to monitor spikes in performance if needed later.

Opening this one up for discussion, as this might or might not be ideal for our architecture.

**Comment by volovyks** [comment]
Seams outdated
