### ISSUE TITLE
allow participants to reject candidates at vote_join()

### ISSUE THREAD

**Issue by ppca** [near/mpc-recovery#418]
Currently the vote_join() logic approves everyone that wants to join. We may want to modify the logic so that the participant can decide to decline a candidate in vote_join().

**Comment by volovyks** [comment]
I don't know if we should have this call. A node can retrieve information about candidates from the contract and then vote according to some criteria. The main question here is - what are these criteria?
It may be a hardcoded vector of "known" participants, staked near, or anything else. cc @DavidM-D

Connected to https://github.com/near/mpc-recovery/issues/353

**Comment by volovyks** [comment]
Discussed this with @DavidM-D. We agreed to introduce an allowlist of NEAR Account IDs (nodes). This list should be set by our partners in Terraform. We will keep `vote_join` for now, but the node will reject it if the account is not on the list.
