### ISSUE TITLE
Github workflow for multichain

### ISSUE THREAD

**Issue by ppca** [near/mpc-recovery#419]
We want the multichain dev env to spin up on a new PR. 
We likely don't need the prod and the testnet flow because we have been only using the manual deploys anyways.

**Comment by volovyks** [comment]
@kmaus-near can you please remind me what was our plan? I think we were planning to move away from PR -> separate env pattern and switch to one dedicated env for PR's that is getting updated by some kind of trigger.

**Comment by kmaus-near** [comment]
Let's just keep the current setup that we have for MPC for the time being, as it seems everyone working on this project is most familiar with it and we've already got it set up. @itegulov had a discussion about it awhile ago and just decided to keep the workflow as is.

I am not up to speed on the plan for multichain or what the infrastructure requirements are (if they are any different), but I'll be getting some more context later today.

**Comment by volovyks** [comment]
Closing in favour of https://github.com/near/mpc-recovery/issues/525
