### ISSUE TITLE
Handle offline nodes in beaver triple generation gracefully

### ISSUE THREAD

**Issue by ChaoticTempest** [near/mpc-recovery#439]
Currently, if a node were to ever go offline, they would not be able to participate in beaver triple generation. The set of participants is hardcoded in triple generation to always include a node even if offline. The protocol will never complete if even one node in the group of participants does not respond. So if one were to go offline, we would halt the whole signature generation pipeline.

To remedy this, online nodes should handle these cases:

1. Check to see if a node is online or not, then include them in the participating set of the beaver triple protocol.
2. Restart triple generation with new set of participants if a participant has been offline for too long.
3. The messages sent needs to include the participating set of online nodes, or have each node evaluate there own set of online nodes. The latter requires reaching a consensus, but is lighter on sending messages across the wire.

We probably want to store this timeout somewhere in the contract, à la genesis config in nearcore. We don't have to worry about the case when there is less than threshold nodes participating, since presignature and signature generation take arbitrary triples. So the nodes that are online can still stockpile up triples if they so wish to.

**Comment by volovyks** [comment]
Blocked on #405
