### ISSUE TITLE
Add new partners to MPC service

### ISSUE THREAD

**Issue by diogoortega** [near/mpc-recovery#442]
Add 4 new partners to the MPC service (listed [here](https://docs.google.com/spreadsheets/d/1o52IO2MVvhCrtpK0RvzBoUWNaMIl5vKv7w3oML0BqHA/edit?usp=sharing), rows 4-7). 
Please ignore any invalid submissions (with invalid data).

Thank you!

**Comment by volovyks** [comment]
We will need to upgrade the SWEAT node since it's using the older codebase version.

**Comment by volovyks** [comment]
@diogoortega I'm closing this issue. Please, create a new one for each specific partner.
