### ISSUE TITLE
Fix multichain contract incurring storage costs without charging

### ISSUE THREAD

**Issue by ChaoticTempest** [near/mpc-recovery#448]
Currently, the multichain contract will store the pending request payloads without taking in any storage fee deposits. This will exhaust the contracts funds especially for very large payloads. We should either be charging a deposit on each `sign` call or momentarily getting rid of old completed requests, as we just wholly store them forever currently.

**Comment by ChaoticTempest** [comment]
The issue here is when and where we call into this check and delete?

- Adding it to `sign` will increase the gas cost and further decrease the stack that we can accumulate to wait for the signature.
- `respond` will likely be a better location but there exist a case where we end up accumulating sign requests but a `respond` was never issued due to something like network is down or is resharing for too long.

**Comment by volovyks** [comment]
Agree. On the one hand, we should do the cleanup in the function that is making the storage size bigger (sign). On the other hand, we want sign to be simple, gas-efficient, and predictable (which will not happen if we do that in 1% of cases).

We can always delete the oldest payload when the new one is submitted. But then we will not have guarantees on how long each payload is available :/
We can also store payloads for each user. If you submit the new one - the old one is getting deleted. But again - no grantees.

**Comment by volovyks** [comment]
With the current design, we delete the payload once the sign transaction succeeds or fails.
