### ISSUE TITLE
Add Sweat Economy to MPC service

### ISSUE THREAD

**Issue by diogoortega** [near/mpc-recovery#469]
Add our partner, Sweat Economy, to the MPC service so they can continue testing.

Details [here](https://docs.google.com/spreadsheets/d/1o52IO2MVvhCrtpK0RvzBoUWNaMIl5vKv7w3oML0BqHA/edit?usp=sharing) (row 8). They'll be using our Testnet relayer.

**Comment by volovyks** [comment]
Added
