### ISSUE TITLE
Node Cohorts

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#485]
### Description

This should help to reduce the number of messages and scale the network better (improve availability).

This design will work the following way:
Participants -> Active Participants -> Cohort

**Comment by ChaoticTempest** [comment]
No longer going to be doing this as we are utilizing participant subsets instead with https://github.com/near/mpc-recovery/pull/446 where presignatures can use a subset of triple participants and signatures can consequently also do the same.
