### ISSUE TITLE
Add Pathfinder to MPC Service

### ISSUE THREAD

**Issue by diogoortega** [near/mpc-recovery#563]
Add Pathfinder to MPC Service --  row 8 in [this sheet](https://docs.google.com/spreadsheets/d/1o52IO2MVvhCrtpK0RvzBoUWNaMIl5vKv7w3oML0BqHA/edit).
Thank you!

**Comment by alenNBH** [comment]
hi @volovyks, any updates on this? Do you need anything additional from my side?


Thank you in advance

**Comment by volovyks** [comment]
@alenNBH it is already added with next parameters on mainnet:
```json
{
        "oidc_provider": {
            "audience": "pathfinder-fastauth-3",
            "issuer": "https://securetoken.google.com/pathfinder-fastauth-3"
        },
        "relayer": {
            "api_key": null,
            "url": "https://nearbalkans.org:3030"
        }
    }
```
Are you experiencing any issues?

**Comment by alenNBH** [comment]
Hi @volovyks, 
The relayer URL is wrongly inserted, it should be with http not https. I thought you will close the ticket after insertion. I will try it out today and will let you know if I have some issues.

Thank you.

**Comment by volovyks** [comment]
@alenNBH probably the reason is something elese. Are you running [https://fast-auth-sdk-frontend-xbgueyzluq-uc.a.run.app](https://fast-auth-sdk-frontend-xbgueyzluq-uc.a.run.app/create-account)? Check the logs and response. We need to know what is the error specifically.

**Comment by alenNBH** [comment]
hi @volovyks, 

Yes, I am trying to create an account from that URL (from /create-account endpoint).
It seems that after verifying mail and creating a passkey application tries to ping https://mpc-recovery-leader-testnet.api.pagoda.co/new_account endpoint from which I got 401 response... 

I can create a video for better understanding if needed.

**Comment by volovyks** [comment]
oh, that explains a lot
ok, added to testnet
