### ISSUE TITLE
Finilize Grafana setup

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#569]
### Description

When I go to Grafana by link ([dev](https://nearinc.grafana.net/d/bdg2srektjy0wd/chain-signatures?orgId=1&refresh=5s&var-node_account_id=All&var-environment=dev) or [partner](https://nearinc.grafana.net/d/bdg2srektjy0wd/chain-signatures?orgId=1&refresh=5s&var-node_account_id=aurora-multichain.testnet&var-node_account_id=bst-near.testnet&var-node_account_id=infstones_nearmpc.testnet&var-node_account_id=lifted-near.testnet&var-node_account_id=mpc-lgns.testnet&var-node_account_id=near-mpc-staking4all-01.testnet&var-node_account_id=nodemonster.testnet&var-node_account_id=pagoda-multichain.testnet&var-environment=testnet)) I'm getting different data compared to the dashboards I navigate using Grafana menus and dev/testnet selector. Probably because of different set of nodes.

### Optional: User Story
As a user, I want to be able to navigate to dev, testnet, and maiinet (later) nashbords using menus and network selector.

**Comment by kmaus-near** [comment]
I might need to sync up on this for clarification. Do we want separate dashboards for each environment (dev, testnet, and soon mainnet)? Or do we just want to keep the selector to switch between nodes running in each environment on the same dashboard (current setup)?

**Comment by volovyks** [comment]
I like what we have now. But it's not that important. I want to be able to navigate to the dashboard without saving setup in the URL.

**Comment by volovyks** [comment]
Done! Thanks!
