### ISSUE TITLE
Real env resharing test

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#573]
### Description

1. Stop one of the nodes
2. Vote for this node to leave using other node credentials
3. Prepare another node (with credentials different from the one that was stopped)
4. Vote for it to join using other participant credentials
5. Check if resharing was successful and MPC is producing signatures

**Comment by ppca** [comment]
doing this on our dev testnet now. Will stop node 7 and add a new node.

**Comment by ppca** [comment]
fixing an issue with node joining here: https://github.com/near/mpc-recovery/pull/612

**Comment by ppca** [comment]
after kicking node 7, the 7 nodes left are not able to start resharing. Likely a state switch problem, need to look into the specifics.

**Comment by ppca** [comment]
Fixed the problem that we don't store new key share to secret manager. Now the resharing is smoonth

**Comment by volovyks** [comment]
@ppca please, close this issue if everything works smoothly
