### ISSUE TITLE
Revisit instructions for integration tests

### ISSUE THREAD

**Issue by mikedotexe** [near/mpc-recovery#577]
### Description

Tried following the README in the integration tests directory, which has:

    docker pull ghcr.io/near/sandbox:latest-aarch64

It looks like we need to make this public perhaps? Not sure where this near/sandbox Docker image is or who to contact next. Nice README, very thorough!

**Comment by volovyks** [comment]
I've made the [sandbox](https://github.com/near/near-sandbox/pkgs/container/sandbox) package public. 
@kmaus-near, @ChaoticTempest ping me if we have a reason to keep it private.
