### ISSUE TITLE
Add Sorbet to MPC service

### ISSUE THREAD

**Issue by diogoortega** [near/mpc-recovery#587]
Add Sorbet (row 9 on this [sheet](https://docs.google.com/spreadsheets/d/1o52IO2MVvhCrtpK0RvzBoUWNaMIl5vKv7w3oML0BqHA/edit?resourcekey#gid=345466892&range=F9)) to Testnet.

Thank you!

**Comment by ChaoticTempest** [comment]
deployed: should be reflected within an hour or two
