### ISSUE TITLE
v2 error: Exceeded the prepaid gas.

### ISSUE THREAD

**Issue by mikedotexe** [near/mpc-recovery#590]
## Description

I saw in Telegram there are multiple versions being deployed, so I'm trying to finish my work using batch FunctionCall Actions to sign Bitcoin input UTXOs in one transaction.

For this ticket, I'm trying to continue forward pointing at `v2.multichain-mpc-dev.testnet`

>Exceeded the prepaid gas.

This was calling the `sign` function. Here's the failed transaction:

https://testnet.nearblocks.io/txns/FK8hzEvq5py2Q3gFY9DjgqwdYQL6tXUn2mhFVsJg2jor

**Comment by volovyks** [comment]
`Exceeded the prepaid gas` is an old version of `Signature was not provided in time` and should never occur now. The fix was merged recently. And we are planning to switch to yield design soon.
If you ever see such an error again - please, reopen this issue.
