### ISSUE TITLE
Deploy latest contract to `v2.multichain-mpc.testnet`

### ISSUE THREAD

**Issue by mikedotexe** [near/mpc-recovery#606]
People in our developer Telegram group have been talking about how they cannot call the official testnet MPC contract from their contract because of the 300 TGas enforcement. I see that it's gone now from the Rust code, but hasn't been deployed to `v2.multichain-mpc.testnet`

This issue is to track someone deploying the current version to the current official testnet version.

<img width="704" alt="Screenshot 2024-05-21 at 8 56 31 PM" src="https://github.com/near/mpc-recovery/assets/1042667/587552f0-69ed-43f5-a2c7-5ecde3646844">

**Comment by volovyks** [comment]
Ok
After this release, you should be able to check the version by calling `version` fn on the contract. Also, the `main` branch will represent what is released to testnet env. (it will represent mainnet later, once we have it).

Related: https://github.com/near/mpc-recovery/pull/609
cc @ppca

**Comment by volovyks** [comment]
@mikedotexe the new version was released
