### ISSUE TITLE
End-to-end synthetic alerts

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#908]
### Description
Our current Alerts do not cover an edge case when the request never reaches our MPC system. I believe that the easiest way of 
fixing this is alert on our Synthetic tests (even if that requires a separate alerting schedule).

**Comment by auto-mausx** [comment]
Revisiting this:

What would be a good endpoint to determine whether or not a request has made it to the MPC System? I think the easiest route to go on this would be to set up a check that pings the start of the request, and waits and confirms at the very end (successful signature sent).

**Comment by volovyks** [comment]
What we have is enough IMO. We are using RPC to send the request. If we receive a signature (response) and check that it's valid, the request reaches MPC.
Maybe I misunderstood you. Please, elaborate.
