### ISSUE TITLE
Setup Grafana VS Code extenison

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#930]
### Description
Since we are now storing Grafana configuration on GitHub, we need to set up the Grafana plugin and add instructions to the repo.

BTW, it should be helpful for  https://github.com/near/mpc/issues/891. We do not need to create a separate dashboard, we can make ours public, add instructions, and share it with validators.

**Comment by volovyks** [comment]
Grafana plugin allows:
- Open a Grafana dashboard JSON file
- Start a live preview of that dashboard inside VS Code, connected to live data from a Grafana instance of your choice
- Edit the dashboard in the preview, using the normal Grafana dashboard editor UI
- From the editor UI, save the updated dashboard back to the original JSON file

**Comment by auto-mausx** [comment]
Created the Grafana token here:
https://start.1password.com/open/i?a=X4SPGO3S3RCI7GGCI37GJOLFCA&v=wj3yy5ls4ehu56mvxw6kaficz4&i=usxiqc2zw2mae6dcivz5uoc3eq&h=signetwork.1password.com

(This is only for people with access to our 1Password)

**Comment by volovyks** [comment]
Cool! Does your local setup work?

**Comment by auto-mausx** [comment]
It does work, quite well actually. This is a great feature for code based grafana dashboards. I don't think it will work for alerting, but for making dashboard changes it will be nice.

**Comment by volovyks** [comment]
Can you please add short instructions so people can set it up? With a reference to Grafana's instruction.
